version: '3.8'

services:
  app:
    build:
      context: .
    image: recipe-app-api:v1
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command:
      sh -c 'python manage.py runserver 0.0.0.0:8000'